spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_data
    username: root
    password: 123456
  application:
    name: big_data
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  jvm:
    args: "--add-exports=java.base/sun.nio.ch=ALL-UNNAMED"
server:
  port: 9090


spark:
  master: local
